version: "2.3"

services:

  monstache:
    image: rwynn/monstache-test
    container_name: c-monstache
    # command: monstache -f /go/src/app/monstache.test.config.toml
    # command: monstache -f ./monstache.test.config.toml
    command: -f ./monstache.test.config.toml
    # command: /bin/monstache -f ./monstache.test.config.toml
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /go/src/app
    volumes:
      - $PWD/monstache.test.config.toml:/go/src/app/monstache.test.config.toml
    depends_on:
      mongo-0:
        condition: service_started
      es6:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: "wget -q -O - http://localhost:8080/healthz"
      interval: 1s
      timeout: 30s
      retries: 300
    restart: unless-stopped

  test-runner:
    image: rwynn/monstache-test-runner
    container_name: c-monstache-test-runner
    command: go test -v
    build:
      context: ./
      dockerfile: ./Dockerfile-test
    working_dir: /go/src/app
    volumes:
      - $PWD:/go/src/app
    depends_on:
      mongo-0:
        condition: service_started
      es6:
        condition: service_healthy
      monstache:
        condition: service_healthy
    environment:
      MONGO_DB_URL: 'mongodb://root-user:password@mongo-0:27017'
      ELASTIC_SEARCH_URL: 'http://es6:9200'
    restart: unless-stopped

  # mongodb:
  #   image: mongo:3.4.14-jessie
  #   container_name: c-mongo
  #   restart: unless-stopped

  mongo-0:
    image: mongo:3.4.14-jessie
    container_name: c-mongo-0
    command: /scripts/mongo-run.sh
    working_dir: /scripts
    volumes:
      - ./mongodb/scripts:/scripts
    ports:
      - "27017:27017"
    # healthcheck:
    #   test: "[ -f /data/health.check ] && exit 0 || exit 1"
    #   interval: 1s
    #   timeout: 30s
    #   retries: 300
    restart: unless-stopped


  es6:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: c-es6
    ports:
      - "9200:9200"
    healthcheck:
      test: "wget -q -O - http://localhost:9200/_cat/health"
      interval: 1s
      timeout: 30s
      retries: 300
    restart: unless-stopped