name: Monstache CI

on:
  push:
    branches: [ rel6 ]
  pull_request:
    branches: [ rel6 ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd docker/test
          ./run-tests.sh
